#!/usr/bin/env python3
from pymongo import MongoClient
import time
import sys

while True:
    print(f"Checking database at {sys.argv[1]}")
    try:
        client = MongoClient(sys.argv[1])
        info = client.server_info()
        print(info)
        print(f"MongoDB ready at {sys.argv[1]}")
        break
    except:
        print(f"Sleeping 5 sec waiting for database at {sys.argv[1]}")
        time.sleep(5)


